packagegroup-balena-connectivity: Remove redundant linux-firmware-iwl…
balena-os/balena-intel pull request #468
Opened 2022-04-20 07:48 UTC by alexgg

…wifi-quz-a0-hr-b0

This package is already included by default.

Changelog-entry: Remove redundant linux-firmware-iwlwifi-quz-a0-hr-b0
Signed-off-by: Alex Gonzalez <alexg@balena.io>

2022-04-20 09:08 UTC, mtoman commented
@alexgg I think we have a loop here that we need to unwind: https://github.com/balena-os/meta-balena/pull/2239 won't build until this is merged and this won't build until the meta-balena PR is merged and bumped here. Since this is done in two steps, between the two the firmware is either double-packaged or is missing altogether, both of which fail the build.

Can we maybe temporarily remove the usage of `iwlwifi-quz-a0-hr-b0` from `layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend` with this PR and then re-introduce it with the meta-balena bump?

2022-04-20 09:11 UTC, mtoman commented
Looking at it more, we should probably also remove the doubled package from `layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_%.bbappend`

2022-04-20 11:43 UTC, mtoman commented
Disregard my other comment, I was living a few days in the past :-/ The only thing wrong here is that `iwlwifi-quz-a0-hr-b0` is referenced in one more place in `backagegroup-balena-connectivity.bbappend`

2022-04-20 14:55 UTC, alexgg commented
> Disregard my other comment, I was living a few days in the past :-/ The only thing wrong here is that `iwlwifi-quz-a0-hr-b0` is referenced in one more place in `backagegroup-balena-connectivity.bbappend`

@mtoman see also https://github.com/balena-os/balena-intel/pull/468

2022-04-20 15:30 UTC, mtoman commented
Yeah, exactly, I was typing faster than thinking. You removed it from
`CONNECTIVITY_FIRMWARES:append:genericx86-64` but it is still specified in `CONNECTIVITY_FIRMWARES` above.

2022-04-20 15:33 UTC, mtoman requested changes

2022-04-20 15:33 UTC, mtoman commented on layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
> -	linux-firmware-iwlwifi-quz-a0-hr-b0 \
This is also pulled above in `CONNECTIVITY_FIRMWARES`

2022-04-21 13:37 UTC, mtoman commented
Replaced by https://github.com/balena-os/balena-intel/pull/469

2022-04-21 13:37 UTC, closed without merging