linux-yocto: Use kernel 5.14
balena-os/balena-intel pull request #502
Opened 2022-05-18 14:33 UTC by DorShahaf

This is needed in order to use the GPU in newer Intel CPUs(Alder Lake).

Changelog-entry: Use kernel 5.14
Signed-off-by: Dor Shahaf <dors@pixellot.tv>

2022-05-19 12:36 UTC, klutchell commented
@resin-jenkins ok to test

2022-05-20 13:55 UTC, floion commented
Hi @DorShahaf for the Intel NUC device type, the latest OS image version `2.98.20` should have a kernel 5.14
Are you not using that device type?

2022-05-20 13:56 UTC, floion requested changes
Currently building this repository would bring kernel version 5.14 for the Intel NUC and the Generic x86-64 Extended device types. So there would be no need for this pull request

2022-05-22 15:44 UTC, DorShahaf commented
Got it, thanks @floion .

2022-05-22 15:44 UTC, closed without merging